### ISSUE TITLE
System font size Large and Largest causes goallist formatting issues

### ISSUE THREAD

**Issue by narthur** [beeminder/beedroid-issues#200] opened 2021-10-29 15:08 UTC
Days to derailment numbers seem to be getting cut off:

![Screenshot_20211029-072919_Beeminder](https://user-images.githubusercontent.com/4655422/139458806-50505fe5-2120-4f50-91e9-8c46ed151502.jpg)

**Comment by dreeves** [comment] 2021-10-29 15:19
I can replicate this by setting my Android system font size to "large"!

**Comment by adamwolf** [comment] 2022-01-05 02:34
This has been reported by another user, and was also caused by large or largest.  This should be something we can handle.  (To be honest, I did not even know this user-adjustable font setting was a thing!)

**Comment by adamwolf** [comment] 2023-02-24 05:02
This is the same/similar to #119.  (Slightly different cause, but same fix!)

**Comment by adamwolf** [comment] 2023-05-08 17:20
This has been released in Beedroid 5.

**Closed as completed by adamwolf** 2023-05-08 17:20 UTC
Labels: BUG, STY, UVI
